name: scorecard-autopopulater

dependencies:
  - beautifulsoup4
  - click
  - flake8
  - isort
  - pip
  - pytest
  - python=3.10
  - requests
  - pip:
    - fake-useragent
    - gspread
    - oauth2client
    - pytest-cov
    - pytz
